### ISSUE TITLE
Powershell version requirements

### ISSUE THREAD

**Issue by Kofl** [petripaavola/Get-IntuneManagementExtensionDiagnostics#1] opened 2023-03-20 09:51 UTC
Hi,

great tool. What are the Powershell version requirements? On version 5 it only errors out

```
Cannot convert value to type "System.Collections.Generic.List`1[System.Management.Automation.PSObject]". Only core
types are supported in this language mode.
At Get-IntuneManagementExtensionDiagnostics.ps1:292 char:1
 $observedTimeline = [System.Collections.Generic.List[PSObject]]@()
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidArgument: (:) [], RuntimeException
     FullyQualifiedErrorId : ConversionSupportedOnlyToCoreTypes
```

**Comment by petripaavola** [comment] 2023-03-20 13:44
Didn't mean to close this thread, reopening it again for further discussion.

**Closed** 2023-03-20 13:43 UTC

**Comment by Kofl** [comment] 2023-03-20 13:49
Thanks, it was indeed "just" the missing running as administrator 
Maybe a check, if the script runs as administrator would be great so others dont run in the issue.

Else: excellent tool for debugging, thanks again

**Comment by petripaavola** [comment] 2023-03-20 13:52
Script does not need to be run as Administrator. It works with normal user permissions. That Constrained Language Mode probably requires Admin rights in your environment.

Thanks for the feedback. There's more coming... :)

**Comment by Kofl** [comment] 2023-03-20 14:03
Ah, verified it - its indeed the Constrained Language Mode. Thanks for clarification.

**Comment by petripaavola** [comment] 2023-03-23 17:52
Closing this issue as this problem was caused by Constrained Language Mode.

It is another story if script can be done to be able to work in Constrained Language Mode.
